version: "3.8"

services:
  app:
    build: .
    environment:
      - DATABASE_PASSWORD
      - CLOUDINARY_KEY
      - CLOUDINARY_SECRET
    ports:
      - "1338:1337"
    volumes:
      - .:/app
      - /app/node_modules
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 250M
        reservations:
          cpus: '0.2'
          memory: 20M